### ISSUE TITLE
error rummage / 2 is undefined or private

### ISSUE THREAD

**Issue by gilbertojuniortelgo** [Excipients/rummage_ecto#33]
I have now done all the procedure that the
https://medium.com/@aditya7iyengar/searching-sorting-and-pagination-in-elixir-phoenix-with-rummage-part-2-8e36558984c2#.dg3dq3y16 after ...
more to no avail.
Error:

(UndefinedFunctionError) function Myapp.rummage / 2 is undefined or private

What could it be?

**Comment by aditya7iyengar** [comment]
Hi @gilbertojuniortelgo. Thanks for reaching out. 
Looking at the above message I think it's the module you're calling `rummage/2` from. `rummage/2` is meant to be called from the model's module, not the application. So, `MyApp.EctoModel.rummage/2`. 

Let me know if this solves it!

**Comment by gilbertojuniortelgo** [comment]
Worse than unsuccessful again.

Error:

(UndefinedFunctionError) function Rummage.Ecto.Myapp.rummage/2 is undefined (module Rummage.Ecto.Myapp is not available)

**Comment by aditya7iyengar** [comment]
@gilbertojuniortelgo Sorry, if I wasn't clear earlier. 

Based on the code you showed, you have to call `rummage/2` function on the model itself (which is `Myapp.Disp` in your case). So you'll be doing something like this:

```elixir
Myapp.Disp.rummage(rummage_params)
```

**Comment by gilbertojuniortelgo** [comment]
No problem :)
Perfect.
Thanks a lot for the help.
